apiVersion: v1
kind: ConfigMap
metadata:
  name: mongodb-config
  namespace: database
data:
  mongod.conf: |
    net:
      port: 27017
      bindIp: 0.0.0.0

    operationProfiling:
      mode: slowOp
      slowOpThresholdMs: 100

    monitoring:
      exporterEnabled: true
      metricsEnabled: true
      
    setParameter:
      enableLocalhostAuthBypass: false
      
    security:
      authorization: enabled
      
    storage:
      wiredTiger:
        engineConfig:
          cacheSizeGB: 1
          journalCompressor: snappy
        collectionConfig:
          blockCompressor: snappy
          
    systemLog:
      destination: file
      path: "/var/log/mongodb/mongod.log"
      logAppend: true
      verbosity: 0
