apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb-exporter
  namespace: database
spec:
  selector:
    matchLabels:
      app: mongodb-exporter
  replicas: 1
  template:
    metadata:
      labels:
        app: mongodb-exporter
    spec:
      containers:
        - name: mongodb-exporter
          image: percona/mongodb_exporter:0.40
          args:
            - --mongodb.uri=mongodb://$(MONGODB_USERNAME):$(MONGODB_PASSWORD)@mongodb:27017/admin
            - --collecting.database
            - --collecting.collection
            - --collecting.topmetrics
          ports:
            - name: metrics
              containerPort: 9216
          env:
            - name: MONGODB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mongodb-secret
                  key: username
            - name: MONGODB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongodb-secret
                  key: password
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb-exporter
  namespace: database
  labels:
    app: mongodb-exporter
  annotations:
    prometheus.io/scrape: 'true'
    prometheus.io/port: '9216'
spec:
  ports:
    - name: metrics
      port: 9216
      targetPort: metrics
  selector:
    app: mongodb-exporter
