apiVersion: v1
kind: Service
metadata:
  name: mongodb
  namespace: database
spec:
  type: ExternalName
  externalName: mongodb-database.svc.cluster.local
  ports:
    - port: 27017
      targetPort: 27017
      name: mongodb
