global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'transaction-service'
    metrics_path: '/api/metrics'
    static_configs:
      - targets: ['host.docker.internal:3001']

  - job_name: 'docker'
    static_configs:
      - targets: ['host.docker.internal:3001']
    metrics_path: '/api/metrics'

  - job_name: 'fluentbit'
    static_configs:
      - targets: ['fluentbit:2020']
