apiVersion: v1
kind: Service
metadata:
  name: loki
  namespace: monitoring
spec:
  type: ExternalName
  externalName: loki-monitoring.svc.cluster.local
  ports:
    - port: 3100
      targetPort: 3100
      name: loki
