apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-exporter
  namespace: database
spec:
  selector:
    matchLabels:
      app: postgres-exporter
  replicas: 1
  template:
    metadata:
      labels:
        app: postgres-exporter
    spec:
      containers:
        - name: postgres-exporter
          image: prometheuscommunity/postgres-exporter:v0.12.0
          ports:
            - containerPort: 9187
              name: metrics
          env:
            - name: DATA_SOURCE_NAME
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: url
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-exporter
  namespace: database
  annotations:
    prometheus.io/scrape: 'true'
    prometheus.io/port: '9187'
spec:
  ports:
    - name: metrics
      port: 9187
      targetPort: metrics
  selector:
    app: postgres-exporter
