apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: database
spec:
  type: ExternalName
  externalName: postgres-database.svc.cluster.local
  ports:
    - port: 5432
      targetPort: 5432
      name: postgres
