apiVersion: v1
kind: ConfigMap
metadata:
  name: fluentbit-config
  namespace: monitoring
data:
  fluent-bit.conf: |
    [SERVICE]
        Flush     1
        Daemon    off
        Log_Level info
        Parsers_File /fluent-bit/etc/parsers.conf
        HTTP_Server On
        HTTP_Listen 0.0.0.0
        HTTP_Port 2020
        storage.path /var/log/flb-storage/
        storage.sync normal
        storage.backlog.mem_limit 5M

    [INPUT]
        Name        forward
        Listen      0.0.0.0
        Port        24224
        Buffer_Chunk_Size 1M
        Buffer_Max_Size 6M

    [INPUT]
        Name              tail
        Path              /var/log/containers/*.log
        Tag               app.*
        Parser            docker
        Refresh_Interval  5
        Mem_Buf_Limit     10MB
        Skip_Long_Lines   On
        DB                /var/log/flb-storage/kube.db

    [FILTER]
        Name                kubernetes
        Match               app.*
        Kube_URL            https://kubernetes.default.svc:443
        Kube_CA_File        /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
        Kube_Token_File     /var/run/secrets/kubernetes.io/serviceaccount/token
        Merge_Log           On
        Merge_Log_Key       log_processed
        K8S-Logging.Parser  On
        K8S-Logging.Exclude On

    [FILTER]
        Name    modify
        Match   *
        Rename  log message
        Add     cluster_name cqrs-es-poc
        Add     env production

    [FILTER]
        Name         grep
        Match        *
        Exclude      $message ^$

    [OUTPUT]
        Name            loki
        Match           *
        Host            loki
        Port            3100
        Labels          job=fluentbit, cluster=cqrs-es-poc
        Label_Keys      $kubernetes['namespace_name'],$kubernetes['pod_name'],$kubernetes['container_name']
        Line_Format     json
        Auto_Kubernetes_Labels On

    [OUTPUT]
        Name        stdout
        Match       *
        Format      json
  parsers.conf: |
    [PARSER]
        Name        docker
        Format      json
        Time_Key    time
        Time_Format %Y-%m-%dT%H:%M:%S.%L
        Time_Keep   On

    [PARSER]
        Name        cqrs_json
        Format      json
        Time_Key    time
        Time_Format %Y-%m-%dT%H:%M:%S.%L
        Time_Keep   On
