apiVersion: v1
kind: ServiceAccount
metadata:
  name: rabbitmq
  namespace: monitoring
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: rabbitmq-role
  namespace: monitoring
rules:
  - apiGroups: ['']
    resources: ['endpoints']
    verbs: ['get']
  - apiGroups: ['']
    resources: ['events']
    verbs: ['create']
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: rabbitmq-rolebinding
  namespace: monitoring
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: rabbitmq-role
subjects:
  - kind: ServiceAccount
    name: rabbitmq
    namespace: monitoring
