apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
      evaluation_interval: 15s

    scrape_configs:
      - job_name: 'prometheus'
        static_configs:
          - targets: ['localhost:9090']

      - job_name: 'cqrs-es-poc'
        metrics_path: /api/metrics
        static_configs:
          - targets: ['cqrs-es-poc-service:3001']

      - job_name: 'rabbitmq'
        static_configs:
          - targets: ['rabbitmq:15692']

      - job_name: 'node-exporter'
        static_configs:
          - targets: ['node-exporter:9100']
