apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: app-monitor
  namespace: monitoring
  labels:
    app: prometheus
spec:
  endpoints:
    - port: http
      path: /api/metrics
      interval: 15s
      scrapeTimeout: 10s
  namespaceSelector:
    matchNames:
      - app
  selector:
    matchLabels:
      app: cqrs-es-poc
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: database-monitor
  namespace: monitoring
  labels:
    app: prometheus
spec:
  endpoints:
    - port: metrics
      interval: 15s
  namespaceSelector:
    matchNames:
      - database
  selector:
    matchExpressions:
      - key: app
        operator: In
        values:
          - mongodb-exporter
          - postgres-exporter
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: messaging-monitor
  namespace: monitoring
  labels:
    app: prometheus
spec:
  endpoints:
    - port: prometheus
      interval: 15s
  namespaceSelector:
    matchNames:
      - monitoring
  selector:
    matchLabels:
      app: rabbitmq
