apiVersion: v1
kind: Service
metadata:
  name: fluent-bit
  namespace: monitoring
  labels:
    app: fluent-bit
spec:
  selector:
    app: fluent-bit
  ports:
    - name: metrics
      port: 2020
      targetPort: 2020
      protocol: TCP
  type: LoadBalancer
