# k8s-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cqrs-app-deployment
  namespace: app
spec:
  replicas: 2 # Iniciar com 2 réplicas
  selector:
    matchLabels:
      app: cqrs-app
  template:
    metadata:
      labels:
        app: cqrs-app
    spec:
      # Remover initContainer por enquanto para o app iniciar corretamente
      containers:
        - name: cqrs-app-container
          # Substitua pela sua imagem Docker correta
          image: ferreirase/cqrs-app:latest # Substitua pela sua imagem real
          imagePullPolicy: Always # Garante que k8s puxe a imagem mais recente
          ports:
            - containerPort: 3001 # Porta que a app escuta (deve bater com PORT no ConfigMap e EXPOSE no Dockerfile)
          envFrom:
            - configMapRef:
                name: app-config # Carrega variáveis do ConfigMap
            - secretRef:
                name: app-secrets # Carrega variáveis do Secret
          readinessProbe:
            httpGet:
              path: /api/health
              port: 3001
            initialDelaySeconds: 15
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 3001
            initialDelaySeconds: 30
            periodSeconds: 20
          startupProbe:
            httpGet:
              path: /api/health
              port: 3001
            failureThreshold: 30
            periodSeconds: 10
          resources:
            requests:
              cpu: '200m'
              memory: '256Mi'
            limits:
              cpu: '500m'
              memory: '512Mi'
            httpGet:
              path: /api/health
              port: 3001
            initialDelaySeconds: 15
            periodSeconds: 10
