apiVersion: apps/v1
kind: Deployment
metadata:
  name: transaction-service
  namespace: app
  labels:
    app: transaction-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: transaction-service
  template:
    metadata:
      labels:
        app: transaction-service
    spec:
      containers:
        - name: transaction-service
          image: ferreirase/cqrs-app:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3001
              name: http
          resources:
            limits:
              cpu: '500m'
              memory: '512Mi'
            requests:
              cpu: '100m'
              memory: '256Mi'
          livenessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 5
            periodSeconds: 5
          envFrom:
            - configMapRef:
                name: app-config
            - secretRef:
                name: app-secrets
---
apiVersion: v1
kind: Service
metadata:
  name: transaction-service
  namespace: app
spec:
  selector:
    app: transaction-service
  ports:
    - port: 3001
      targetPort: 3001
      name: http
  type: ClusterIP
