apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
type: Opaque
stringData: # Usar stringData é mais fácil, k8s codifica para base64
  RABBITMQ_PASSWORD: 'admin'
  POSTGRES_PASSWORD: 'postgres' # A senha do usuário 'user'
  MONGO_PASSWORD: 'admin'
