apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: app
type: Opaque
stringData:
  MONGO_PASSWORD: 'mongodb'
  POSTGRES_PASSWORD: 'postgres'
  RABBITMQ_PASSWORD: 'admin'
  LOKI_PASSWORD: 'admin'
